### ISSUE TITLE
Why TimedElasticBand::autoResize did not use a kind of interpolation?

### ISSUE THREAD

**Issue by NeoPhix** [rst-tu-dortmund/teb_local_planner#104]
I have an interesting question:

Why the method 

`void TimedElasticBand::autoResize(double dt_ref, double dt_hysteresis, int min_samples, int max_samples, bool fast_mode)`

did not use interpolation for obtaining the poses array with known stable time differences? The first glance on implementation shows that linear interpolation could be more optimal for this situation.

Is there some magic that I do not see? What don't I understand? 

Thank you for your answer!

**Comment by croesmann** [comment]
Hi @NeoPhix,

good question. The reason is basically historic. 
At the time of coding, everything was working fine by just changing the trajectory slightly (inserting or removing a single pose in every outer-loop iteration) and to let the optimizer do the rest. And I am not experiencing  any issues with resizing even now.

Of course, you can improve the warm-start for subsequent iterations by resampling the complete trajectory using linear interpolation (similar to Matlab's `interp1` method).
I am doing this in my (to be published) c++ code for time optimal feedback control of general systems.
And it works fine, yes. I have not performed any benchmarks yet in comparison to the teb_local_planner implementation, but I guess the overhead of the current _resizing_ implementation is negligible (based on my observations). 
Furthermore, we are adding/removing only a single pose every outer-loop iteration. 
You can also, of course, change the linear search strategy to something more efficient. You can even guess the required number of poses based on the previous optimization result
(just some trivial math based on linear interpolation). However, I observed that changing the number of grid points more aggressively, the performance sometimes decreases in more complex scenarios since the optimizer needs to recover much more optimization variables at once from a _possibly_ poor warm-start/initial guess.
