### ISSUE TITLE
min. turning radius higher than 5m

### ISSUE THREAD

**Issue by glebos** [rst-tu-dortmund/teb_local_planner#14]
Hello,

is it possible to apply a min. turning radius higher than 5m?

Kind regards.

**Comment by beetleskin** [comment]
Speaking of config limits, is there a reason to limit the velocity to 2m/ss?

**Comment by croesmann** [comment]
There are no theoretical reasons for the limits. I set them according to my use cases and haven't thought about general cases in the past. 

According to the min turning radius there are just practical limitations:
If the minimum turning radius is substantially high (hence only small steering angles are allowed) the problem size drastically increases: The trajectory length could be huge since the robot must often switch moving directions (alternating forward and backward motions) in order to achieve a desired pose. Despite the fact that the computation time increases, the constraint approximation could be less restrictive and hence leading to solutions that are not feasible for the real robot.

I am going to update the code soon, since currently I do not have spare-time left.
Same for issue #15.

**Comment by croesmann** [comment]
I changed the upper bounds in commit 216fe3d.
If you need further adjustments, please let me know.

Note, optimization weights and _dt_ref_ as well as _dt_hyst_ are not
tuned for velocities and accelerations beyond the default values (e.g. >1 m/s). 
Just increasing the maximum velocity bounds without adjusting the other parameters might lead to an insufficient behavior.

**Comment by beetleskin** [comment]
Thanks a lot for the adjustments. Do you have further suggestions when driving with lets say 20m/s?

**Comment by glebos** [comment]
Thank you very much for the adjustments, appreciate it!
