### ISSUE TITLE
How to add obstacles to the scene

### ISSUE THREAD

**Issue by tcjcxy30** [rst-tu-dortmund/teb_local_planner#44]
Hello:
I want to add some movable obstacles to the scene in order to get the sensor reading from  laser scanner and then avoid obstacles while planning trajectory. How can I do this in Tutorial 9 with stage simulator? Tutorial 9 only simply adding a Rviz Cylinder type marker but  i want to add movable obstacles in stage simulator and that can be seen at rviz?
Please advise.

**Comment by croesmann** [comment]
Hi,

tutorial 9 demonstrates how to publish custom obstacles via message. Since you want to add dynamic obstacles to stage you need to proceed in the following way:

1. configure stage with multiple robots (1 actual robot and all others are obstacles)
2. for all obstacle "robots" create a small ros-node that provides them with velocity commands
   in order to make them "dynamic".
3. for navigation:
 a. obstacles should be automatically detected by your costmap obstacle layer (but yes, they are treated statically in each sampling interval).
 b. or publish from your node which commands the obstacles in stage also the custom obstacle message required by the teb_local_planner (e.g. like in tutorial 9).

_Note: dynamic obstacles are not yet fully supported. They are treated as static obstacle in each sampling interval (like for all planners in the navigation stack). I am going to push an update of the planner with actual support for dynamic obstacles this summer._

I close this issue for now. If you have further questions, please just leave a comment.
