### ISSUE TITLE
Unexpected robot oscillations even with tutorial example

### ISSUE THREAD

**Issue by even1024** [rst-tu-dortmund/teb_local_planner#64]
https://www.youtube.com/watch?v=VLvRT5gb7_I
https://www.youtube.com/watch?v=Dq411vE3jpg

Issue #2 is clear to me because robot had to do U-turn in advance before it's too late, but issue #1 looks to me like a bug.

**Comment by croesmann** [comment]
Indeed, issue 2 is a local minimum problem and can only be solved in case the global planner provides sufficient information on the orientation along the global plan.

Today I solved a serious issue which led to poor closed-loop performances. The robot should now move closer to the global plan. However, this does not completely solve issue 1.
If you look closer to the planned trajectory at 59seconds and later, you will see that the trajectory is not smooth. The discrete trajectory points (red arrows) are jumping around. This is due to the obstacle avoidance "force" pushing them away (since the constraint is violated!). If you slightly reduce the `min_obstacle_dist`, the robot should be able to pass. I am going to reinvestigate the default parameters of the tutorials package.
If you have any further questions please feel free to comment or reopen this issue.
