### ISSUE TITLE
Error in calculation of roadmap area with roadmap_graph_area_length_scale set unequal to 1.0

### ISSUE THREAD

**Issue by littlelordy** [rst-tu-dortmund/teb_local_planner#68]
First of all: great work with your planner, I really like it.

I think I found an error in the calculation of the roadmap area. 
In line [254](https://github.com/rst-tu-dortmund/teb_local_planner/blob/kinetic-devel/src/graph_search.cpp#L254) of graph_search.cpp you set the x start position of the roadmap area on the connecting vector between start and goal according to the parameter roadmap_graph_area_length_scale. If I'm right this is supposed to be something like an offset to the start_position. But if that's right, there is no point in the 0.5 factor.
So to clarify what I mean:
your current code is:
`area_origin = start + 0.5*(1.0-roadmap_graph_area_length_scale)*start_goal_dist*diff.normalized() - 0.5*area_width*normal;`
but I think it should be:
`area_origin = start + (1.0-roadmap_graph_area_length_scale)*start_goal_dist*diff.normalized() - 0.5*area_width*normal;`

**Comment by croesmann** [comment]
Hi @littlelordy,
thanks for your feedback! The reason for the 0.5 is that I intended to scale both ends of the roadmap area, so to add an offset to both start and end. Otherwise, in case of adding an offset to the start, you are totally right.
However, I am not yet sure which strategy might be better suited since I have no use-case yet. If you have any ideas, please let me know :-)

**Comment by littlelordy** [comment]
Ok, I see. Thanks for the reply. :-)
I am currently too busy with other work, but if I'll happen to find some time, I may test one strategy against the other.
