### ISSUE TITLE
Car like robot navigation

### ISSUE THREAD

**Issue by ArtlyStyles** [rst-tu-dortmund/teb_local_planner#87]
Hi, I am building a MIT-Racecar. It has LiDAR, ZED stereo camera, Ackerman drive, and VESC. I am looking for a navigation stack for car-like-robot since I have issues with DWA local planner because my robot can not rotate in place. I heard teb_local_planner can be used for Car-like-robot with ackerman. Could anyone explain:

1. If Teb can handle no-in-place rotation?
2. What parameters should I use for car like robot?

Thanks,

**Comment by croesmann** [comment]
Hi,

1. yes.

2. please have a look at the example:
`roslauch teb_local_planner_tutorials robot_carlike_in_stage.launch` and all its parameter and configuration files.
You might also check out the [tutorials section](http://wiki.ros.org/teb_local_planner/Tutorials).

Note, this question is better placed on [answers.ros.org](http://answers.ros.org) since it does not describe any issue and it could be interesting for other users as well.
