### ISSUE TITLE
differential model robot got stuck in a local optimal trajectory

### ISSUE THREAD

**Issue by Kanelankai** [rst-tu-dortmund/teb_local_planner#88]
Hello!
I downloaded the kinetic-devel package and use it for local path planning with turtlebot3 in gazebo.
I found the robot still easily got stuck in a local optimal trajectory.
In teb_local_planner ROS wiki, it said that this problem had been solve by optimizing a subset of admissible trajectories of distinctive topologies in parallel. 
I don't know whether the package which I'm using can also optimizing a subset of trajectories. 
What can I do to solve this problem?
Thank  you very much.

**Comment by croesmann** [comment]
Hi,
what global planner are you using? you still need a global planner to avoid to get stuck in local minima (in the static map).
However, the parallel planning is just for avoiding local minimas w.r.t. small obstacles (e.g. humans or other robots) in the local costmap.
I would recommend to complete all the [tutorials](http://wiki.ros.org/teb_local_planner/Tutorials) and to check the [teb_local_planners_tutorials](http://wiki.ros.org/teb_local_planner_tutorials) package.

_Note, this question is better placed on [answers.ros.org](http://answers.ros.org) since it does not describe any issue and it could be interesting for other users as well._
