### ISSUE TITLE
min_vel_x and min_vel_theata option?

### ISSUE THREAD

**Issue by mertmzk** [rst-tu-dortmund/teb_local_planner#96]
Hi all,

There is no option of setting minimum values for velocity x and theate in parameters. Is there any way of doing it in a quicker way?

Thanks

**Comment by subodh-malgonde** [comment]
I was looking for the same options. For some reason teb_local_planner generates very low forward velocities (Eg 0.18) even when the `max_vel_x` is set to 2.0.

**EDIT**: Found a related issue https://github.com/rst-tu-dortmund/teb_local_planner/issues/10 which addresses this problem.

**Comment by croesmann** [comment]
I close this in favor of #10 which suggests modifying the low-level controller.
However, this introduces a model mismatch between planning and the actual robot. In case if `min_vel_x`
is low, this might be neglectable.

On the other hand, since the controller operates time-optimally, changing the maximum acceleration (in combination with dt_ref) should result in higher initial velocities. Configuring the acceleration limits carefully is crucial.

If you have still problems, please feel free to add comments and we can reopen the issue.
